### ISSUE TITLE
Possibility to "materialize" blank nodes

### ISSUE THREAD

**Issue by leipert** [seebi/rdf.sh#13]
I have a document with blank nodes. I want each blank node to be converted to a resource.

e.g.
```
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
<urn:example:shape>
    a sh:NodeShape ;
    sh:property [
        sh:datatype xsd:integer ;
        sh:message "ID must be a number" ;
        sh:name "ID" ;
        sh:path <urn:example:id>
    ]
.
```
should be converted to
```
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
<urn:example:shape>
    a sh:NodeShape ;
    sh:property <urn:generated:A924E218-632F-4328-8D52-EFC48D784C5D>
.

<urn:generated:A924E218-632F-4328-8D52-EFC48D784C5D>
        sh:datatype xsd:integer ;
        sh:message "ID must be a number" ;
        sh:name "ID" ;
        sh:path <urn:example:id>
.
```

The CLI should provide a parameter for an URI template `urn:example:{uuid}` where `{uuid}` will be replaced with an uuid. Have a look into `uuidgen` to generate uuid's in the command line.

Thank you for your hard work.

**Comment by seebi** [comment]
like it ...

**Comment by seebi** [comment]
useful links regarding blank nodes:

- https://www.insight-centre.org/sites/default/files/publications/blank_nodes_jws.pdf
- https://www.w3.org/wiki/BnodeSkolemization
- http://richard.cyganiak.de/blog/2011/03/blank-nodes-considered-harmful/

so real skolemization is out of scope I think, but also just a simple materialisation can be useful.

**Comment by seebi** [comment]
@leipert please validate the feature ...
